---

# Set Repository
- name: Add PostgreSQL Key Repository
  apt_key: 
  url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  state: present

- name: Add PostgreSQL Repository
  repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
  state: present
  filename: pgdb

# Postgresql Install 
- name: Ensure PostgreSQL Pyhon libraries are installed.
  apt:
          name: "{{ postgresql_python_library }}"
          state: present 

- name: Ensure PostgreSQL packages are installed
  apt:
          name: "{{ postgresql_packages }}"
          state: present
          notify: restart postgresql

- name: Check if postgreSQL database is initialized.
  stat:
          path: "{{ postgresql_data_dir }}/PG_VERSION"
          register: pgdata_dir_version
         
- name: Ensure PostgreSQL database is initialized.
  command: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true

