galaxy_info:
  author: Henrique Rocha 
  description: 4linux Infrastructure Analyst
  company: 4linux

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.4

 platforms:
 - name: Debian
   versions: 10

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
